baseURL: "https://www.robertallenhill.com/"
title: "Robert Allen Hill"
paginate: 7
theme: papermod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
        menu:
            main:
                - name: About
                  url: about/
                  weight: 5
                - name: Posts
                  url: posts/
                  weight: 1
                - name: Tags
                  url: tags
                  weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    #author: Robert Hill
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    # ShowShareButtons: true
    # ShowReadingTime: true
    # disableSpecial1stPost: true
    # displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true

    # profileMode:
    #     enabled: false
    #     #imageUrl: "#"
    #     #imageTitle: my image
    #     # imageWidth: 120
    #     # imageHeight: 120
    homeInfoParams:
        Content: My semi-rarely updated journal where where I can muse on topics in tech, bicycles, tools, and other nerdery. I am mostly using this to condition myself to write more often, and to reduce my usage of social media services.
        buttons:
            - name: Posts
              url: posts/
            - name: About
              url: about/
            - name: Tags
              url: tags

  #  homeInfoParams:
  #     Content: >
  #          Welcome to my personal website, where I'll be writing about things I care about.
    socialIcons:
        - name: github
          url: "https://github.com/robert-hill"
        - name: Mastodon
          url: "https://rah.social/@robert"
        - name: RsS
          url: "index.xml"

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true