name: Update Infrastructure and deploy website code

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
    # Checkout this repo
    - uses: actions/checkout@v2

    # Download a specific Terraform version you'd like to use
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.3
        terraform_wrapper: false

    # Ensure you have AWS credentials set up. Your config will likely differ here
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    # Apply the Terraform code
    - run: terraform init
    - run: terraform validate
    - run: terraform plan -out planfile
    - run: terraform apply planfile

    # Upload our website code to our origin S3 bucket
    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./public s3://$(terraform output s3_bucket | cut -d '"' -f2) --delete