name: "Deploy Terraform Production code"

on:
  push:
    branches:
    - main

jobs: 
  deploy:
    name: "Deploy - Production"
    needs: terraform
    if: github.ref == 'refs/heads/main' 
    defaults:
      run: 
        working-directory: "."
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v2
      - 
        name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-region: us-west-2
          aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - 
        name: "Setup themes"
        run: "git submodule update --init --recursive"
      - 
        name: "Update theme to Latest commit"
        run: "git submodule update --remote --merge"
      - 
        name: "Setup hugo"
        uses: peaceiris/actions-hugo@v2
        with: 
          hugo-version: latest
      - 
        name: Build
        run: "hugo --gc --verbose --minify"
      - 
        name: "Deploy static site to S3 bucket"
        run: "aws s3 sync ./public s3://rhill-vcard-website-origin/ --delete --cache-control 'max-age=0, must-revalidate, proxy-revalidate, public'"