name: "Staging Terraform"

on:
  pull_request:
    branches:
    - main
    paths:
      - '**.tf'
 terraform-staging:
    name: "Terraform - Staging"
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: "./terraform/staging"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - 
        uses: hashicorp/setup-terraform@v1
        with: 
          terraform_version: "1.1.3"
          terraform_wrapper: false
      - 
        name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-region: us-west-2
          aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Terraform Init
        id: init
        run: terraform init -no-color
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        if: github.event_name == 'pull_request'
        run: terraform apply -auto-approve
